/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClubsRouteImport } from './routes/clubs'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as ClubsClubIdRouteImport } from './routes/clubs.$clubId'

const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsRoute = ClubsRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => EventsRoute,
} as any)
const ClubsClubIdRoute = ClubsClubIdRouteImport.update({
  id: '/$clubId',
  path: '/$clubId',
  getParentRoute: () => ClubsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clubs': typeof ClubsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRouteWithChildren
  '/players': typeof PlayersRoute
  '/profile': typeof ProfileRoute
  '/rankings': typeof RankingsRoute
  '/clubs/$clubId': typeof ClubsClubIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clubs': typeof ClubsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRouteWithChildren
  '/players': typeof PlayersRoute
  '/profile': typeof ProfileRoute
  '/rankings': typeof RankingsRoute
  '/clubs/$clubId': typeof ClubsClubIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clubs': typeof ClubsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRouteWithChildren
  '/players': typeof PlayersRoute
  '/profile': typeof ProfileRoute
  '/rankings': typeof RankingsRoute
  '/clubs/$clubId': typeof ClubsClubIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/clubs'
    | '/dashboard'
    | '/events'
    | '/players'
    | '/profile'
    | '/rankings'
    | '/clubs/$clubId'
    | '/events/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/clubs'
    | '/dashboard'
    | '/events'
    | '/players'
    | '/profile'
    | '/rankings'
    | '/clubs/$clubId'
    | '/events/$eventId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/clubs'
    | '/dashboard'
    | '/events'
    | '/players'
    | '/profile'
    | '/rankings'
    | '/clubs/$clubId'
    | '/events/$eventId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ClubsRoute: typeof ClubsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  EventsRoute: typeof EventsRouteWithChildren
  PlayersRoute: typeof PlayersRoute
  ProfileRoute: typeof ProfileRoute
  RankingsRoute: typeof RankingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs': {
      id: '/clubs'
      path: '/clubs'
      fullPath: '/clubs'
      preLoaderRoute: typeof ClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/clubs/$clubId': {
      id: '/clubs/$clubId'
      path: '/$clubId'
      fullPath: '/clubs/$clubId'
      preLoaderRoute: typeof ClubsClubIdRouteImport
      parentRoute: typeof ClubsRoute
    }
  }
}

interface ClubsRouteChildren {
  ClubsClubIdRoute: typeof ClubsClubIdRoute
}

const ClubsRouteChildren: ClubsRouteChildren = {
  ClubsClubIdRoute: ClubsClubIdRoute,
}

const ClubsRouteWithChildren = ClubsRoute._addFileChildren(ClubsRouteChildren)

interface EventsRouteChildren {
  EventsEventIdRoute: typeof EventsEventIdRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsEventIdRoute: EventsEventIdRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ClubsRoute: ClubsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  EventsRoute: EventsRouteWithChildren,
  PlayersRoute: PlayersRoute,
  ProfileRoute: ProfileRoute,
  RankingsRoute: RankingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
